from gym.envs.registration import register
from .games import *
from d4rl import infos
import os

DATASET_URLS = {}
ALL_ENVS = []

ALL_LEVELS = DMLAB_30 + psychlab + psychlab_memory + psychlab_visuospatial + fast_mapping + others

GENERATED_LEVELS = gen_explore_goal_locations + \
    gen_explore_object_locations + gen_explore_object_rewards + \
    gen_explore_obstructed_goals + gen_lasertag

NEW_GEN_LEVELS = gen_explore_goal_locations + \
    gen_explore_object_locations + gen_explore_object_rewards + \
    gen_explore_obstructed_goals + gen_lasertag

CACHE_AVAILABLE = [
    "new_explore_goal_locations-69-expert-v0",
    "new_explore_goal_locations-55-expert-v0",
    "new_explore_object_rewards-15-expert-v0",
    "new_explore_obstructed_goals-14-expert-v0",
    "new_explore_obstructed_goals-33-expert-v0",
    "new_explore_object_rewards-68-expert-v0",
    "new_explore_goal_locations-41-expert-v0",
    "new_explore_obstructed_goals-39-expert-v0",
    "new_explore_object_rewards-10-expert-v0",
    "new_explore_obstructed_goals-3-expert-v0",
    "new_explore_obstructed_goals-17-expert-v0",
    "new_explore_object_rewards-24-expert-v0",
    "new_explore_obstructed_goals-54-expert-v0",
    "new_explore_obstructed_goals-19-expert-v0",
    "new_explore_object_rewards-79-expert-v0",
    "new_explore_object_rewards-73-expert-v0",
    "new_explore_obstructed_goals-6-expert-v0",
    "new_explore_goal_locations-68-expert-v0",
    "new_explore_obstructed_goals-48-expert-v0",
    "new_explore_object_rewards-11-expert-v0",
    "new_explore_obstructed_goals-31-expert-v0",
    "new_explore_object_rewards-9-expert-v0",
    "new_explore_object_rewards-52-expert-v0",
    "new_explore_obstructed_goals-55-expert-v0",
    "new_explore_obstructed_goals-13-expert-v0",
    "new_explore_object_rewards-12-expert-v0",
    "new_explore_goal_locations-56-expert-v0",
    "new_explore_object_rewards-39-expert-v0",
    "new_explore_object_rewards-54-expert-v0",
    "new_explore_goal_locations-45-expert-v0",
    "new_explore_obstructed_goals-9-expert-v0",
    "new_explore_object_rewards-44-expert-v0",
    "new_explore_object_rewards-41-expert-v0",
    "new_explore_object_rewards-77-expert-v0",
    "new_explore_obstructed_goals-42-expert-v0",
    "new_explore_obstructed_goals-44-expert-v0",
    "new_explore_obstructed_goals-59-expert-v0",
    "new_explore_object_rewards-20-expert-v0",
    "new_explore_goal_locations-65-expert-v0",
    "new_explore_goal_locations-51-expert-v0",
    "new_explore_obstructed_goals-25-expert-v0",
    "new_explore_goal_locations-57-expert-v0",
    "new_explore_goal_locations-60-expert-v0",
    "new_explore_obstructed_goals-0-expert-v0",
    "new_explore_goal_locations-49-expert-v0",
    "new_explore_goal_locations-61-expert-v0",
    "new_explore_obstructed_goals-12-expert-v0",
    "new_explore_object_rewards-49-expert-v0",
    "new_explore_goal_locations-47-expert-v0",
    "new_explore_obstructed_goals-52-expert-v0",
    "new_explore_object_rewards-43-expert-v0",
    "new_explore_object_rewards-38-expert-v0",
    "new_explore_object_rewards-50-expert-v0",
    "new_explore_object_rewards-75-expert-v0",
    "new_explore_obstructed_goals-56-expert-v0",
    "new_explore_object_rewards-67-expert-v0",
    "new_explore_obstructed_goals-5-expert-v0",
    "new_explore_object_rewards-63-expert-v0",
    "new_explore_obstructed_goals-50-expert-v0",
    "new_explore_obstructed_goals-20-expert-v0",
    "new_explore_goal_locations-53-expert-v0",
    "new_explore_obstructed_goals-53-expert-v0",
    "new_explore_object_rewards-80-expert-v0",
    "new_explore_object_rewards-33-expert-v0",
    "new_explore_obstructed_goals-38-expert-v0",
    "new_explore_obstructed_goals-2-expert-v0",
    "new_explore_goal_locations-40-expert-v0",
    "new_explore_obstructed_goals-32-expert-v0",
    "new_explore_object_rewards-40-expert-v0",
    "new_explore_object_rewards-46-expert-v0",
    "new_explore_goal_locations-71-expert-v0",
    "new_explore_object_rewards-30-expert-v0",
    "new_explore_object_rewards-13-expert-v0",
    "new_explore_object_rewards-51-expert-v0",
    "new_explore_obstructed_goals-57-expert-v0",
    "new_explore_obstructed_goals-8-expert-v0",
    "new_explore_object_rewards-16-expert-v0",
    "new_explore_object_rewards-26-expert-v0",
    "new_explore_obstructed_goals-24-expert-v0",
    "new_explore_obstructed_goals-47-expert-v0",
    "new_explore_obstructed_goals-37-expert-v0",
    "new_explore_object_rewards-21-expert-v0",
    "new_explore_object_rewards-42-expert-v0",
    "new_explore_obstructed_goals-36-expert-v0",
    "new_explore_goal_locations-66-expert-v0",
    "new_explore_obstructed_goals-18-expert-v0",
    "new_explore_object_rewards-78-expert-v0",
    "new_explore_goal_locations-46-expert-v0",
    "new_explore_goal_locations-44-expert-v0",
    "new_explore_object_rewards-61-expert-v0",
    "new_explore_obstructed_goals-60-expert-v0",
    "new_explore_object_rewards-18-expert-v0",
    "new_explore_obstructed_goals-51-expert-v0",
    "new_explore_object_rewards-70-expert-v0",
    "new_explore_obstructed_goals-45-expert-v0",
    "new_explore_obstructed_goals-46-expert-v0",
    "new_explore_obstructed_goals-58-expert-v0",
    "new_explore_object_rewards-37-expert-v0",
    "new_explore_object_rewards-22-expert-v0",
    "new_explore_goal_locations-42-expert-v0",
    "new_explore_object_rewards-66-expert-v0",
    "new_explore_obstructed_goals-16-expert-v0",
    "new_explore_obstructed_goals-35-expert-v0",
    "lasertag-94-expert-v0",
    "new_explore_object_rewards-74-expert-v0",
    "new_explore_obstructed_goals-41-expert-v0",
    "new_explore_goal_locations-62-expert-v0",
    "new_explore_goal_locations-48-expert-v0",
    "new_explore_object_rewards-14-expert-v0",
    "new_explore_obstructed_goals-10-expert-v0",
    "new_explore_goal_locations-50-expert-v0",
    "new_explore_object_rewards-65-expert-v0",
    "new_explore_object_rewards-17-expert-v0",
    "new_explore_goal_locations-67-expert-v0",
    "new_explore_object_rewards-69-expert-v0",
    "new_explore_obstructed_goals-61-expert-v0",
    "new_explore_object_rewards-53-expert-v0",
    "new_explore_obstructed_goals-1-expert-v0",
    "new_explore_object_rewards-23-expert-v0",
    "new_explore_object_rewards-71-expert-v0",
    "new_explore_obstructed_goals-23-expert-v0",
    "new_explore_object_rewards-64-expert-v0",
    "new_explore_object_rewards-57-expert-v0",
    "new_explore_object_rewards-19-expert-v0",
    "new_explore_goal_locations-54-expert-v0",
    "new_explore_object_rewards-47-expert-v0",
    "new_explore_goal_locations-43-expert-v0",
    "new_explore_obstructed_goals-27-expert-v0",
    "new_explore_obstructed_goals-22-expert-v0",
    "new_explore_goal_locations-59-expert-v0",
    "new_explore_obstructed_goals-28-expert-v0",
    "new_explore_obstructed_goals-11-expert-v0",
    "new_explore_obstructed_goals-15-expert-v0",
    "new_explore_object_rewards-25-expert-v0",
    "new_explore_goal_locations-63-expert-v0",
    "new_explore_obstructed_goals-7-expert-v0",
    "new_explore_object_rewards-45-expert-v0",
    "new_explore_obstructed_goals-40-expert-v0",
    "new_explore_object_rewards-60-expert-v0",
    "new_explore_object_rewards-72-expert-v0",
    "new_explore_obstructed_goals-4-expert-v0",
    "new_explore_obstructed_goals-43-expert-v0",
    "new_explore_object_rewards-48-expert-v0",
    "new_explore_obstructed_goals-21-expert-v0",
    "new_explore_object_rewards-76-expert-v0",
    "new_explore_obstructed_goals-49-expert-v0",
    "new_explore_object_rewards-36-expert-v0",
    "new_explore_obstructed_goals-29-expert-v0",
    "lasertag-29-expert-v0",
    "new_explore_goal_locations-20-expert-v0",
    "lasertag-1-expert-v0",
    "lasertag-23-expert-v0",
    "lasertag-24-expert-v0",
    "lasertag-25-expert-v0",
    "lasertag-0-expert-v0",
    "lasertag-5-expert-v0",
    "new_explore_goal_locations-21-expert-v0",
    "lasertag-22-expert-v0",
    "lasertag-7-expert-v0",
    "lasertag-106-expert-v0",
    "lasertag-4-expert-v0",
    "lasertag-28-expert-v0",
    "new_explore_goal_locations-24-expert-v0",
    "new_explore_goal_locations-23-expert-v0",
    "lasertag-105-expert-v0",
    "lasertag-107-expert-v0",
    "lasertag-3-expert-v0",
    "lasertag-20-expert-v0",
    "lasertag-21-expert-v0",
    "lasertag-27-expert-v0",
    "lasertag-103-expert-v0",
    "lasertag-2-expert-v0",
    "lasertag-6-expert-v0",
    "lasertag-104-expert-v0",
    "lasertag-26-expert-v0",
    "new_explore_goal_locations-22-expert-v0",
    "lasertag-8-expert-v0",
    "lasertag-9-expert-v0",
    "new_explore_object_locations-31-expert-v0",
    "lasertag-82-expert-v0",
    "new_explore_object_locations-28-expert-v0",
    "new_explore_object_locations-1-expert-v0",
    "new_explore_object_locations-36-expert-v0",
    "new_explore_object_locations-29-expert-v0",
    "new_explore_object_locations-17-expert-v0",
    "lasertag-83-expert-v0",
    "new_explore_object_locations-12-expert-v0",
    "new_explore_object_locations-26-expert-v0",
    "new_explore_object_locations-23-expert-v0",
    "new_explore_object_locations-24-expert-v0",
    "new_explore_object_locations-11-expert-v0",
    "new_explore_object_locations-6-expert-v0",
    "new_explore_object_locations-20-expert-v0",
    "new_explore_object_locations-37-expert-v0",
    "new_explore_object_locations-33-expert-v0",
    "new_explore_object_locations-5-expert-v0",
    "new_explore_object_locations-34-expert-v0",
    "new_explore_object_locations-19-expert-v0",
    "lasertag-41-expert-v0",
    "new_explore_object_locations-21-expert-v0",
    "new_explore_object_locations-0-expert-v0",
    "new_explore_object_locations-32-expert-v0",
    "new_explore_object_locations-15-expert-v0",
    "lasertag-44-expert-v0",
    "new_explore_object_locations-39-expert-v0",
    "new_explore_object_locations-4-expert-v0",
    "new_explore_object_locations-25-expert-v0",
    "new_explore_object_locations-3-expert-v0",
    "new_explore_object_locations-35-expert-v0",
    "new_explore_object_locations-16-expert-v0",
    "new_explore_object_locations-9-expert-v0",
    "new_explore_object_locations-14-expert-v0",
    "new_explore_object_locations-38-expert-v0",
    "lasertag-43-expert-v0",
    "new_explore_object_locations-2-expert-v0",
    "new_explore_object_locations-10-expert-v0",
    "new_explore_object_locations-18-expert-v0",
    "new_explore_object_locations-30-expert-v0",
    "new_explore_object_locations-7-expert-v0",
    "new_explore_object_locations-27-expert-v0",
    "lasertag-84-expert-v0",
    "new_explore_object_locations-22-expert-v0",
    "lasertag-42-expert-v0",
    "new_explore_object_locations-8-expert-v0",
    "lasertag-81-expert-v0",
    "new_explore_object_locations-13-expert-v0",
    "lasertag-40-expert-v0",
    "lasertag-58-expert-v0",
    "lasertag-88-expert-v0",
    "lasertag-85-expert-v0",
    "lasertag-59-expert-v0",
    "lasertag-55-expert-v0",
    "lasertag-87-expert-v0",
    "lasertag-57-expert-v0",
    "lasertag-86-expert-v0",
    "lasertag-56-expert-v0",
    "lasertag-69-expert-v0",
    "lasertag-54-expert-v0",
    "new_explore_goal_locations-3-expert-v0",
    "lasertag-78-expert-v0",
    "lasertag-64-expert-v0",
    "new_explore_goal_locations-0-expert-v0",
    "lasertag-60-expert-v0",
    "new_explore_goal_locations-4-expert-v0",
    "new_explore_goal_locations-9-expert-v0",
    "lasertag-52-expert-v0",
    "lasertag-66-expert-v0",
    "new_explore_goal_locations-1-expert-v0",
    "new_explore_goal_locations-7-expert-v0",
    "lasertag-51-expert-v0",
    "lasertag-72-expert-v0",
    "lasertag-65-expert-v0",
    "new_explore_goal_locations-6-expert-v0",
    "lasertag-50-expert-v0",
    "new_explore_goal_locations-5-expert-v0",
    "lasertag-77-expert-v0",
    "new_explore_goal_locations-8-expert-v0",
    "new_explore_goal_locations-2-expert-v0",
    "lasertag-45-expert-v0",
    "lasertag-101-expert-v0",
    "new_explore_goal_locations-10-expert-v0",
    "new_explore_goal_locations-13-expert-v0",
    "lasertag-49-expert-v0",
    "lasertag-47-expert-v0",
    "new_explore_goal_locations-14-expert-v0",
    "lasertag-46-expert-v0",
    "new_explore_goal_locations-11-expert-v0",
    "lasertag-48-expert-v0",
    "lasertag-100-expert-v0",
    "new_explore_goal_locations-12-expert-v0",
    "new_explore_goal_locations-36-expert-v0",
    "new_explore_goal_locations-26-expert-v0",
    "new_explore_goal_locations-25-expert-v0",
    "new_explore_goal_locations-39-expert-v0",
    "new_explore_goal_locations-37-expert-v0",
    "new_explore_goal_locations-27-expert-v0",
    "new_explore_goal_locations-33-expert-v0",
    "new_explore_goal_locations-29-expert-v0",
    "new_explore_goal_locations-35-expert-v0",
    "new_explore_goal_locations-30-expert-v0",
    "new_explore_goal_locations-32-expert-v0",
    "new_explore_goal_locations-38-expert-v0",
    "new_explore_goal_locations-34-expert-v0",
    "new_explore_goal_locations-31-expert-v0",
    "new_explore_goal_locations-28-expert-v0",
    "new_explore_goal_locations-15-expert-v0",
    "lasertag-80-expert-v0",
    "new_explore_goal_locations-18-expert-v0",
    "new_explore_goal_locations-17-expert-v0",
    "new_explore_goal_locations-19-expert-v0",
    "new_explore_goal_locations-16-expert-v0",
    "lasertag-35-expert-v0",
    "new_explore_object_locations-42-expert-v0",
    "lasertag-18-expert-v0",
    "new_explore_object_locations-46-expert-v0",
    "lasertag-31-expert-v0",
    "new_explore_object_locations-41-expert-v0",
    "lasertag-12-expert-v0",
    "lasertag-15-expert-v0",
    "lasertag-36-expert-v0",
    "new_explore_object_locations-47-expert-v0",
    "lasertag-19-expert-v0",
    "new_explore_object_locations-40-expert-v0",
    "lasertag-33-expert-v0",
    "lasertag-32-expert-v0",
    "lasertag-13-expert-v0",
    "lasertag-11-expert-v0",
    "lasertag-39-expert-v0",
    "lasertag-14-expert-v0",
    "lasertag-89-expert-v0",
    "lasertag-37-expert-v0",
    "lasertag-92-expert-v0",
    "lasertag-10-expert-v0",
    "lasertag-16-expert-v0",
    "lasertag-34-expert-v0",
    "lasertag-91-expert-v0",
    "lasertag-93-expert-v0",
    "new_explore_object_locations-45-expert-v0",
    "new_explore_object_locations-43-expert-v0",
    "lasertag-17-expert-v0",
    "lasertag-90-expert-v0",
    "lasertag-102-expert-v0",
    "lasertag-38-expert-v0",
    "new_explore_object_locations-44-expert-v0",
    "lasertag-30-expert-v0",
    "new_explore_obstructed_goals-74-expert-v0",
    "lasertag-68-expert-v0",
    "new_explore_obstructed_goals-86-expert-v0",
    "new_explore_obstructed_goals-73-expert-v0",
    "new_explore_obstructed_goals-75-expert-v0",
    "new_explore_obstructed_goals-90-expert-v0",
    "new_explore_obstructed_goals-76-expert-v0",
    "new_explore_obstructed_goals-72-expert-v0",
    "new_explore_obstructed_goals-96-expert-v0",
    "new_explore_obstructed_goals-84-expert-v0",
    "new_explore_obstructed_goals-77-expert-v0",
    "lasertag-97-expert-v0",
    "new_explore_obstructed_goals-88-expert-v0",
    "new_explore_obstructed_goals-97-expert-v0",
    "new_explore_obstructed_goals-80-expert-v0",
    "new_explore_obstructed_goals-79-expert-v0",
    "new_explore_obstructed_goals-101-expert-v0",
    "lasertag-95-expert-v0",
    "lasertag-79-expert-v0",
    "new_explore_obstructed_goals-103-expert-v0",
    "new_explore_obstructed_goals-87-expert-v0",
    "lasertag-75-expert-v0",
    "new_explore_obstructed_goals-95-expert-v0",
    "lasertag-61-expert-v0",
    "lasertag-62-expert-v0",
    "new_explore_obstructed_goals-64-expert-v0",
    "new_explore_obstructed_goals-107-expert-v0",
    "new_explore_obstructed_goals-81-expert-v0",
    "lasertag-63-expert-v0",
    "new_explore_obstructed_goals-82-expert-v0",
    "new_explore_obstructed_goals-69-expert-v0",
    "lasertag-70-expert-v0",
    "new_explore_obstructed_goals-89-expert-v0",
    "new_explore_obstructed_goals-105-expert-v0",
    "new_explore_obstructed_goals-67-expert-v0",
    "new_explore_obstructed_goals-78-expert-v0",
    "lasertag-67-expert-v0",
    "new_explore_obstructed_goals-99-expert-v0",
    "new_explore_obstructed_goals-94-expert-v0",
    "new_explore_obstructed_goals-91-expert-v0",
    "lasertag-71-expert-v0",
    "new_explore_obstructed_goals-100-expert-v0",
    "lasertag-76-expert-v0",
    "new_explore_obstructed_goals-71-expert-v0",
    "new_explore_goal_locations-64-expert-v0",
    "lasertag-74-expert-v0",
    "new_explore_obstructed_goals-85-expert-v0",
    "new_explore_obstructed_goals-83-expert-v0",
    "new_explore_goal_locations-58-expert-v0",
    "new_explore_obstructed_goals-104-expert-v0",
    "new_explore_goal_locations-70-expert-v0",
    "new_explore_obstructed_goals-63-expert-v0",
    "lasertag-96-expert-v0",
    "lasertag-99-expert-v0",
    "lasertag-73-expert-v0",
    "new_explore_goal_locations-52-expert-v0",
    "new_explore_obstructed_goals-93-expert-v0",
    "new_explore_obstructed_goals-65-expert-v0",
    "new_explore_obstructed_goals-92-expert-v0",
    "new_explore_obstructed_goals-68-expert-v0",
    "lasertag-98-expert-v0",
    "lasertag-53-expert-v0",
]

dataset_pos = {
    'dgx05': ['explore_goal_locations_large',
              'explore_object_locations_large',
              'explore_object_rewards_few',
              'explore_obstructed_goals_large',
              'nav_maze_static_01',
              'skymaze_irreversible_path_varied',
              'explore_goal_locations_small',
              'explore_object_locations_small',
              'explore_object_rewards_many',
              'explore_obstructed_goals_small',
              'skymaze_irreversible_path_hard',
              ],
    'dgx08': ['psychlab_arbitrary_visuomotor_mapping',
              'rooms_collect_good_objects_train',
              'rooms_keys_doors_puzzle',
              'rooms_watermaze',
              'psychlab_continuous_recognition',
              'rooms_exploit_deferred_effects_train',
              'rooms_select_nonmatching_object',
              ],
    'dgx09': ['natlab_fixed_large_map',
              'natlab_varying_map_randomized',
              'natlab_varying_map_regrowth',
              'nav_maze_static_02',
              'nav_maze_static_03',
              'seekavoid_arena_01',
              'stairway_to_melon',
              ],
    'dgx10': ['lasertag-' + str(i) for i in range(10, 20)] + ['lasertag-' + str(i) for i in range(30, 40)], 
}

for game in ALL_LEVELS:
    cur_game = None
    for taskset in tasksets.items():
        if game in taskset[1]:
            cur_game = os.path.join(tasksets_path[taskset[0]], game)
    position = ''
    for pos in dataset_pos.keys():
        if game in dataset_pos[pos]:
            position = pos
            break
    env_name = '%s-expert-v0' % game
    ALL_ENVS.append(env_name)
    register(
        id=env_name,
        entry_point='d4rl.dmlab.envs:OfflineDMLABEnv',
        kwargs={
            'game': cur_game,
            'gen_id': 0,
            'dataset_name': game,
            'extra_input': False if game not in languages else True,
            'ref_min_score': infos.REF_MIN_SCORE.get(env_name, None),
            'ref_max_score': infos.REF_MAX_SCORE.get(env_name, None),
            'is_test': False,
            'task_group': 'dmlab',
            'dataset_pos': position,
            'cache_path': None,
            'seed': 0,
            'num_action_repeats': 4,
        }
    )

for game in NEW_GEN_LEVELS:
    cur_game = None
    for taskset in tasksets.items():
        if game in taskset[1]:
            cur_game = os.path.join('new_gen_levels', tasksets_path[taskset[0]] + '_new', game)
    game = 'new_' + game
    position = ''
    for pos in dataset_pos.keys():
        if game in dataset_pos[pos]:
            position = pos
            break
    env_name = '%s-expert-v0' % game
    ALL_ENVS.append(env_name)
    register(
        id=env_name,
        entry_point='d4rl.dmlab.envs:OfflineDMLABEnv',
        kwargs={
            'game': cur_game,
            'gen_id': 1,
            'dataset_name': game,
            'extra_input': False if game not in languages else True,
            'ref_min_score': infos.REF_MIN_SCORE.get(env_name, None),
            'ref_max_score': infos.REF_MAX_SCORE.get(env_name, None),
            'is_test': False,
            'task_group': 'dmlab',
            'dataset_pos': position,
            'cache_path': None,
            'seed': 0,
            'num_action_repeats': 4,
        }
    )

for game in GENERATED_LEVELS:
    cur_game = None
    for taskset in tasksets.items():
        if game in taskset[1]:
            cur_game = os.path.join('old_gen_levels', tasksets_path[taskset[0]], game)
    position = ''
    for pos in dataset_pos.keys():
        if game in dataset_pos[pos]:
            position = pos
            break
    env_name = '%s-expert-v0' % game
    ALL_ENVS.append(env_name)
    register(
        id=env_name,
        entry_point='d4rl.dmlab.envs:OfflineDMLABEnv',
        kwargs={
            'game': cur_game,
            'gen_id': -1,
            'dataset_name': game,
            'extra_input': False if game not in languages else True,
            'ref_min_score': infos.REF_MIN_SCORE.get(env_name, None),
            'ref_max_score': infos.REF_MAX_SCORE.get(env_name, None),
            'is_test': False,
            'task_group': 'dmlab',
            'dataset_pos': position,
            'cache_path': None,
            'seed': 0,
            'num_action_repeats': 4,
        }
    )